### ISSUE TITLE
🐛 Bug: Unecessary horizontal scroll

### ISSUE THREAD

**Issue by Sahillather002** [uclaacm/recursion-lab#233]
### Is there an existing issue for this?

- [ ] I have searched existing issues

### What happened?

Unecessary Horizontal Scroll on the home page
![image](https://github.com/uclaacm/recursion-lab/assets/72077931/21ceee06-6328-486c-b48b-b64a145751c2)

**Comment by EDWIN1669086** [comment]
@Sahillather002 yes, issue #222
