### ISSUE TITLE
🐾 Minor Update: Move 'X' button in Sidebar to leftside

### ISSUE THREAD

**Issue by Sahillather002** [uclaacm/recursion-lab#234]
### Context
We have a sidebar navigation that allows us to click the "X" or outside of the sidebar in order to close it.

![image](https://github.com/uclaacm/recursion-lab/assets/72077931/0390314b-ce5c-4368-9d5e-a4048e9e21b9)
![image](https://github.com/uclaacm/recursion-lab/assets/72077931/7fa08c5b-af2f-4118-85ac-98d9cbf7f551)

### Problem
When we click to open the sidebar on the far left, the 'X' is on the far right, which forces the user to navigate from left to right (bad UX). Instead, having it at the same place as the hamburger icon improves UX.

_Note that the global text centering applies here, so that's why it's centered (and we made it right aligned rigidly)_

### Solution
Make the 'X' button left-aligned. You'll probably have to use both `text-align:left` and `text-align:center` explicitly or use flexbox. 

**Disclaimer:** do not remove body { text-align: center; } It's a necessary evil, at this point in the project.

**Comment by EDWIN1669086** [comment]
Yea, that's a decent idea. Feel free to add that change.
