### ISSUE TITLE
🚀 Feature: Disable Checkmark button on no input

### ISSUE THREAD

**Issue by EDWIN1669086** [uclaacm/recursion-lab#261]
### Context
This issue pertains to KhanCard. Despite the user not entering any values, we are allowed to click "Check" and receive a validation on our "answers".

<img width="990" alt="image" src="https://github.com/uclaacm/recursion-lab/assets/43260874/ef4a5bf0-6733-49b4-a4a8-c18fd511630e">

### Problem
To the user, this seems to be a bug. We do not want to allow a check on something that does not exist.

### Proposed Solution
This issue arises because of the model of KhanCard. The control is in the hands of Dropdown/KhanInput to update whether or not the answer is correct. KhanCard only knows whether the answer is correct or not (through a boolean array). It has no visibility on what the answers are. 

---

This is a :rocket: Feature Request

**Comment by RahulKhanna14** [comment]
Please refer to slack message I sent/will send in a few minutes! There is an issue with local storage that makes this functionality difficult to implement.
