### ISSUE TITLE
🚀 Feature: Create a "Finish the Code" Component (shared)

### ISSUE THREAD

**Issue by EDWIN1669086** [uclaacm/recursion-lab#43]
Allows the user to write code through a "fill in the blank" style of learning. 

### Use Case

Basically used on every page to get the user to write code and see the output.

### Proposed Solution
<img width="818" alt="Screenshot 2023-04-19 at 2 33 27 PM" src="https://user-images.githubusercontent.com/43260874/233205200-8eec5df2-8d18-4e75-8db8-ebe64c9feb6c.png">

_See the KhanCard component for guidance_

- [x] Create the component and place it in the shared components/shared folder
- [x] Style the component so it visually looks like the Figma reference (except with Dropdown, not KhanInput)
- [x] ^^ Do not use the KhanInput. Use the DropDown component. Example is on on Mario page.
- [x] Implement the functionality of "Tries Left" dots, Show Answer, and displaying the Correct and Incorrect explanations
_Up to this point, the idea is the same as KhanCard_
- [x] Implement the Output box (by passing the problem function to your card component and displaying that answer)

**Comment by EDWIN1669086** [comment]
@tylerdtran This will be your final issue request for Sprint 1. More content needs to be created to continue working on your page, but this component will be useful to all pages.

**Comment by tylerdtran** [comment]
FinishCode Component has been complete
